import type {
  AiInsight,
  AutomationReport,
  Client,
  EmailCampaignReport,
  FlashyAccount,
  NewsletterPlan,
  SmsCampaignReport,
} from "./types";

export const clients: Client[] = [
  {
    id: "client-glow",
    name: "Glow Cosmetics",
    owner: "דנה לוי",
    industry: "איקומרס ביוטי",
    visibleModules: ["reports", "planner", "ai"],
  },
  {
    id: "client-home",
    name: "HomeStyle",
    owner: "אורי כהן",
    industry: "ריהוט ועיצוב הבית",
    visibleModules: ["reports", "planner"],
  },
  {
    id: "client-fit",
    name: "FitFuel",
    owner: "מאיה רוזן",
    industry: "תוספי תזונה",
    visibleModules: ["reports", "ai"],
  },
];

export const flashyAccounts: FlashyAccount[] = [
  {
    id: "acc-glow",
    clientId: "client-glow",
    flashyAccountId: 246,
    name: "Glow Cosmetics IL",
    website: "https://glow.example",
    currency: "ILS",
    timezone: "Asia/Jerusalem",
    credits: 4820,
    usdIlsRate: 3.7,
    smsCreditPriceUsd: 0.12,
    monthlySubscriptionCostUsd: 39,
    agencyRetainerCostIls: 4200,
    active: true,
    lastSyncAt: "2026-05-19T05:35:00.000Z",
  },
  {
    id: "acc-home",
    clientId: "client-home",
    flashyAccountId: 5125,
    name: "HomeStyle",
    website: "https://home.example",
    currency: "ILS",
    timezone: "Asia/Jerusalem",
    credits: 1890,
    usdIlsRate: 3.7,
    smsCreditPriceUsd: 0.14,
    monthlySubscriptionCostUsd: 29,
    agencyRetainerCostIls: 2800,
    active: true,
    lastSyncAt: "2026-05-19T04:15:00.000Z",
  },
  {
    id: "acc-fit",
    clientId: "client-fit",
    flashyAccountId: 477,
    name: "FitFuel DTC",
    website: "https://fit.example",
    currency: "ILS",
    timezone: "Asia/Jerusalem",
    credits: 7360,
    usdIlsRate: 3.7,
    smsCreditPriceUsd: 0.11,
    monthlySubscriptionCostUsd: 49,
    agencyRetainerCostIls: 3600,
    active: true,
    lastSyncAt: "2026-05-19T03:50:00.000Z",
  },
];

export const emailReports: EmailCampaignReport[] = [
  {
    id: "email-1",
    accountId: "acc-glow",
    campaignId: 2001,
    campaignName: "השקת סרום ויטמין C",
    subjectLine: "הסרום שהלקוחות חיכו לו חזר למלאי",
    sentAt: "2026-05-05T07:45:00.000Z",
    totalRecipients: 18420,
    totalDelivered: 18110,
    totalOpens: 8290,
    uniqueClicks: 1180,
    totalClicks: 1745,
    purchases: 162,
    revenueGenerated: 48210,
    totalBounces: 310,
    unsubscribed: 36,
    spam: 2,
  },
  {
    id: "email-2",
    accountId: "acc-glow",
    campaignId: 2002,
    campaignName: "מדריך שגרת ערב",
    subjectLine: "3 צעדים לשגרת ערב שעובדת",
    sentAt: "2026-05-12T17:20:00.000Z",
    totalRecipients: 17680,
    totalDelivered: 17420,
    totalOpens: 7240,
    uniqueClicks: 910,
    totalClicks: 1320,
    purchases: 88,
    revenueGenerated: 25180,
    totalBounces: 260,
    unsubscribed: 28,
    spam: 1,
  },
  {
    id: "email-3",
    accountId: "acc-home",
    campaignId: 3101,
    campaignName: "סייל פינות אוכל",
    subjectLine: "פינת האוכל החדשה שלך מחכה",
    sentAt: "2026-05-08T08:30:00.000Z",
    totalRecipients: 9400,
    totalDelivered: 9210,
    totalOpens: 3440,
    uniqueClicks: 520,
    totalClicks: 688,
    purchases: 31,
    revenueGenerated: 58720,
    totalBounces: 190,
    unsubscribed: 19,
    spam: 0,
  },
  {
    id: "email-4",
    accountId: "acc-fit",
    campaignId: 4101,
    campaignName: "Bundle חיטוב",
    subjectLine: "הבאנו את הבאנדל שמקל על שגרת האימון",
    sentAt: "2026-05-09T06:10:00.000Z",
    totalRecipients: 12200,
    totalDelivered: 11980,
    totalOpens: 4715,
    uniqueClicks: 1025,
    totalClicks: 1510,
    purchases: 118,
    revenueGenerated: 38940,
    totalBounces: 220,
    unsubscribed: 25,
    spam: 1,
  },
];

export const smsReports: SmsCampaignReport[] = [
  {
    id: "sms-1",
    accountId: "acc-glow",
    campaignId: 9001,
    campaignName: "תזכורת סוף מבצע",
    sentAt: "2026-05-06T15:30:00.000Z",
    totalRecipients: 6420,
    totalDelivered: 6280,
    uniqueClicks: 760,
    totalClicks: 812,
    purchases: 96,
    revenueGenerated: 30980,
    unsubscribed: 18,
  },
  {
    id: "sms-2",
    accountId: "acc-home",
    campaignId: 9201,
    campaignName: "קופון משלוח חינם",
    sentAt: "2026-05-10T13:00:00.000Z",
    totalRecipients: 2210,
    totalDelivered: 2168,
    uniqueClicks: 244,
    totalClicks: 286,
    purchases: 19,
    revenueGenerated: 31840,
    unsubscribed: 9,
  },
  {
    id: "sms-3",
    accountId: "acc-fit",
    campaignId: 9301,
    campaignName: "חלון 24 שעות",
    sentAt: "2026-05-11T16:10:00.000Z",
    totalRecipients: 5140,
    totalDelivered: 5030,
    uniqueClicks: 690,
    totalClicks: 774,
    purchases: 75,
    revenueGenerated: 25560,
    unsubscribed: 13,
  },
];

export const automationReports: AutomationReport[] = [
  {
    id: "auto-1",
    accountId: "acc-glow",
    automationId: 477,
    automationName: "נטישת עגלה - 3 שלבים",
    channel: "email",
    date: "2026-05-14",
    totalRecipients: 920,
    totalDelivered: 905,
    totalOpens: 518,
    totalClicks: 168,
    purchases: 44,
    revenueGenerated: 18440,
  },
  {
    id: "auto-2",
    accountId: "acc-glow",
    automationId: 478,
    automationName: "SMS נטישת עגלה",
    channel: "sms",
    date: "2026-05-14",
    totalRecipients: 480,
    totalDelivered: 468,
    totalOpens: 0,
    totalClicks: 92,
    purchases: 29,
    revenueGenerated: 12110,
  },
  {
    id: "auto-3",
    accountId: "acc-home",
    automationId: 601,
    automationName: "ברוכים הבאים",
    channel: "email",
    date: "2026-05-15",
    totalRecipients: 310,
    totalDelivered: 306,
    totalOpens: 182,
    totalClicks: 34,
    purchases: 8,
    revenueGenerated: 12600,
  },
  {
    id: "auto-4",
    accountId: "acc-fit",
    automationId: 740,
    automationName: "רכישה חוזרת אחרי 21 יום",
    channel: "email",
    date: "2026-05-16",
    totalRecipients: 620,
    totalDelivered: 612,
    totalOpens: 352,
    totalClicks: 140,
    purchases: 49,
    revenueGenerated: 16690,
  },
  {
    id: "auto-5",
    accountId: "acc-fit",
    automationId: 741,
    automationName: "SMS השלמת הזמנה",
    channel: "sms",
    date: "2026-05-16",
    totalRecipients: 260,
    totalDelivered: 256,
    totalOpens: 0,
    totalClicks: 44,
    purchases: 16,
    revenueGenerated: 5820,
  },
];

export const newsletterPlans: NewsletterPlan[] = [
  {
    id: "plan-1",
    clientId: "client-glow",
    accountId: "acc-glow",
    date: "2026-05-21",
    channel: "email",
    kind: "campaign",
    status: "ready",
    title: "ניוזלטר: שגרת קיץ",
    owner: "דנה",
    notes: "להכניס בלוק לפני/אחרי וקישור לקטגוריית SPF.",
    flashyUrl: "https://my.flashy.app",
    assetUrl: "https://drive.google.com",
  },
  {
    id: "plan-2",
    clientId: "client-glow",
    accountId: "acc-glow",
    date: "2026-05-24",
    channel: "sms",
    kind: "campaign",
    status: "draft",
    title: "SMS סוף חודש",
    owner: "יובל",
    notes: "לבדוק מלאי סרום לפני שליחה.",
  },
  {
    id: "plan-3",
    clientId: "client-home",
    accountId: "acc-home",
    date: "2026-05-26",
    channel: "email",
    kind: "campaign",
    status: "approved",
    title: "מדריך בחירת ספה",
    owner: "אורי",
    notes: "לחבר לעמוד קטגוריית סלונים.",
  },
  {
    id: "plan-4",
    clientId: "client-fit",
    accountId: "acc-fit",
    date: "2026-05-28",
    channel: "email",
    kind: "automation",
    status: "ready",
    title: "שיפור סדרת רכישה חוזרת",
    owner: "מאיה",
    notes: "להוסיף פיצול לפי מוצר שנרכש.",
  },
];

export const aiInsights: AiInsight[] = [
  {
    id: "ai-1",
    clientId: "client-glow",
    category: "send_time",
    priority: "high",
    title: "חלון השליחה של 07:30-08:30 מוביל באימייל",
    body: "קמפיינים שנשלחו בבוקר יצרו שיעור פתיחה גבוה בכ-18% ושיעור רכישה יציב יותר לעומת ערב.",
    action: "לתכנן את שני הניוזלטרים הבאים לשעות הבוקר ולשמור SMS לשעות אחר הצהריים.",
  },
  {
    id: "ai-2",
    clientId: "client-glow",
    category: "subject",
    priority: "medium",
    title: "שורות נושא עם מוצר ספציפי מנצחות",
    body: "שורת הנושא של הסרום יצרה יותר קליקים מנושא תוכני כללי על שגרת ערב.",
    action: "להעדיף נושא שמציין מוצר/קטגוריה ברורה כבר בשורה הראשונה.",
  },
  {
    id: "ai-3",
    clientId: "client-fit",
    category: "automation",
    priority: "high",
    title: "אוטומציית רכישה חוזרת היא מנוע צמיחה",
    body: "האוטומציה יצרה יחס הכנסה לנמען גבוה יותר מכל קמפיין אחר החודש.",
    action: "להוסיף וריאציה לפי קטגוריית מוצר ולבדוק SMS תומך ביום 24.",
  },
];
